
//#pragma autoinclude(0)//This would normally autoinclude this file based on a priority
#include "../ECS/ECS.c"

/*
//If you uncomment this entire block, it still gets syntax highlighted and intellisensed correctly. That's by design. 
//I didn't want to break the tools I was already using for vanilla C development because I am procrastinating rewriting them all myself.

//Some context of the below. That's what I type while developing my game. Everything after "#pragma _system" is the C code that actually gets generated by my preprocessor.
#pragma system
void ExampleSystem(){
	UsingComp(Position, pos)
	UsingComp(Gravity, grav)
	printf("System()\n");
	pos.y -= grav.strength;
}
#pragma _system
*/


void _ExampleSystem(ChunkIteratorArgs iterArgs){
	GetStream(Position);
	GetStream(Gravity);
	floop{
		Position* pos = UseStream(Position);
		Gravity* grav = UseStream(Gravity);
		
		printf("System()\n");
		(*pos).y -= (*grav).strength;
	}
}

void ExampleSystem(){
	Query(Sig_Create(toE(Position), toE(Gravity)), _ExampleSystem);
}